# config file version
apiVersion: 1

deleteDatasources:
  - name: Scraper (mlab-oti)
    orgId: 1
  - name: Scraper (mlab-staging)
    orgId: 1
  - name: Scraper (mlab-sandbox)
    orgId: 1

  - name: Downloader (mlab-oti)
    orgId: 1
  - name: Downloader (mlab-staging)
    orgId: 1
  - name: Downloader (mlab-sandbox)
    orgId: 1
