apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bigquery-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bigquery-exporter
  template:
    metadata:
      labels:
        run: bigquery-exporter
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: bigquery-exporter
        image: measurementlab/prometheus-bigquery-exporter:v1.0.0
        args: [ "-project={{GCLOUD_PROJECT}}",
                "-gauge-query=/queries/bq_mlabns_ratelimit.sql",
                "-gauge-query=/queries/bq_mlabns_sixhour_requests.sql",
                "-gauge-query=/queries/bq_annotation.sql",
                "-gauge-query=/queries/bq_gardener_parse_time.sql",
                "-gauge-query=/queries/bq_ndt_s2c.sql",
              ]
        ports:
        - containerPort: 9348
        volumeMounts:
        - mountPath: /queries
          name: bigquery-config

      volumes:
      - name: bigquery-config
        configMap:
          name: bigquery-exporter-config
